"""constantes para teste"""

#canvas e geometria
GAME_WIDTH = 700
GAME_HEIGHT = 700
PIXEL_SIZE = 10
HEIGHT_PROPORTIONS = int((GAME_HEIGHT / PIXEL_SIZE) - 1)
WIDTH_PROPORTIONS = int((GAME_WIDTH / PIXEL_SIZE) - 1)
BODY_PARTS = 3

#cores
#SNAKE_COLOR = "#00FF00" #verde
APPLE_COLOR = "#FF0000" #vermelho
LEMON_COLOR = "#73f461" #verde
ORANGE_COLOR = "#f4750f" #laranja
WALL_COLOR = "#47504a" #cinza
BACKGROUND_COLOR = "#263D42" #
